application: open-order
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

# Static files
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static
  static_dir: static

# Backend / Static
- url: /backend
  static_files: static/backend/views/index.html
  upload: static/backend/views/index.html
- url: /backend/(.*\.html)
  static_files: static/backend/views/\1
  upload: static/backend/views/(.*\.html)

# Frontend / Static
- url: /frontend
  static_dir: static/frontend

# App
- url: /api/doc
  static_dir: static/api
  http_headers:
    Access-Control-Allow-Origin: '*'
- url: /api/.*
  script: main.app

# Redirect to frontend
- url: /
  static_files: static/frontend/index.html
  upload: static/frontend/index.html
- url: /.*
  static_dir: static/frontend

libraries:
- name: webapp2
  version: "2.5.1"
